### PR TITLE
convert profiling into util. reorg main.py

### PR DESCRIPTION
**Pull request by tmf97**
### Summary

This PR make profiling.py into a nifty utility that profiles a run of main.py, and has the same command line interface options as main.py

### Testing

Ran `python tests/profiling.py configs/freefall.json -v` and then opened with `snakeviz for_snakeviz.prof`, worked great.

### Notes

The architecture of putting everything in a file into a "main" function that you can import easily into other files is very underrated and underused. Let's use it more! For reference: [check this out!](https://www.youtube.com/watch?v=g_wlZ9IhbTs)

### Comments
- [x] Add an x between the brackets if you commented your code well!

### CODE REVIEW

**Review by adamrnasir — APPROVED** [review]
Looks awesome, would like to use for statetime_rehash to determine source of slowdown

**Review by andrew032011 — APPROVED** [review]
Looks good!

**Review by yolandaw2021 — COMMENTED** [review]
Looks great! Understood the idiom better!

**Review by yolandaw2021 — COMMENTED** [review]
The snakeviz profile page looks good!

**Pull request merged**
