### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by sjz38**
### Summary

This PR addresses Jira ticket [CISLUNAR-144](https://jira.cornell.edu/browse/CISLUNAR-144)     
This PR introduces autodoc generation via sphinx. The infrastructure is contained within the `docs/` folder.  I also added README which explains some important points. You can see what the site looks like here https://cislunarsim.readthedocs.io/en/latest/. Once merged into `master` I'll change it to deploy based upon the `master` branch. 

I need to update this branch from `master`, but I want to talk about what we want in the 'v0.0.1' of the site (if we want to add docstrings for everything we have already, of hold off). Also want to get a few more eyes on this.

### Testing

Added an example docstring to the [Actuator Model](https://cislunarsim.readthedocs.io/en/latest/core.models.html?highlight=actuator), which generates properly.

### Notes

This is just a starting point for documentation, we can obviously take this much further...

### Comments
- [ ] Add an x between the brackets if you commented your code well!

### CODE REVIEW

**Review by tmf97 — COMMENTED** [review]
Lookin good!
We won't need the `__init__.py` files once #6 is in

**Review by tmf97 — APPROVED** [review]
Solid stuff, love the website!

**Comment by sjz38** [comment]
> Lookin good! We won't need the `__init__.py` files once #6 is in

Not 100% sure if we would be able to get rid of `__init__.py` files because Sphinx needs to see each src folder as a separate package. Perhaps I should hold off on merging until #6 goes through?

**Comment by tmf97** [comment]
Nah just get it in, I'll deal with it later

**Review by adamrnasir — APPROVED** [review]
Noticed that toctree maxdepth option is different across different files (4 in modules.rst and core.rst, 2 in index.rst). Looks like it relates to the table of contents header nesting depth, do we want it consistent throughout? Does it matter?

Assuming needs no change, everything looks great!

**Comment by sjz38** [comment]
> Noticed that toctree maxdepth option is different across different files (4 in modules.rst and core.rst, 2 in index.rst). Looks like it relates to the table of contents header nesting depth, do we want it consistent throughout? Does it matter?
> 
> Assuming needs no change, everything looks great!

@adamrnasir `modules.rst` and `core.rst` (along with a lot of other `.rst` files are auto generated. However `index.rst` is the one that is not. We could probably play with that value, but let's look at that at a later time if it gives us any issues.

**Pull request merged**
