### PR TITLE
remove init files

### PR DESCRIPTION
**Pull request by tmf97**
### Summary

This PR cleans up all `__init__.py` files, which are no longer needed now that we have a `setup.py`

### Testing

Existing units tests and pyright

### Comments
- [N/A] Add an x between the brackets if you commented your code well!

### CODE REVIEW

**Comment by sjz38** [comment]
I still want to see if the sphinx docs need these `__init__.py` files. Still trying to fix some issues that occurred with the docs over the past few PRs, so lets hold off on merging this for at least a little bit

**Comment by tmf97** [comment]
Roger, holding off.

**Comment by sjz38** [comment]
`__init__` files, unfortunately, need to be present for the sphinx docs to work. Thoughts on closing this PR? @tmf97

**Comment by tmf97** [comment]
Rip, yeah closing

**Pull request closed without merging**
