### PR TITLE
Fix Config.py and make Config class immutable.

### PR DESCRIPTION
**Pull request by yolandaw2021**
### Summary
Instead of using dataclasses, I used a class variable "_frozen" to implement the immutable state of the class. Now the Config class can be initialized but not mutated.

### Testing
I added three tests for immutability that make sure MutationException will be thrown when changes are made. 

### Comments
- [x] Add an x between the brackets if you commented your code well!

### CODE REVIEW

**Comment by tmf97** [comment]
Solid! Let's fix the merge conflicts and fix some of the pyright errors in `config.py`

**Comment by andrew032011** [comment]
The rest of it looks fine to me!

**Review by tmf97 — APPROVED** [review]
Looks solid!

**Comment by yolandaw2021** [comment]
Should we delete the ci branch? Or do we add more to it for future changes?

**Pull request merged**
